// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsSender is an autogenerated mock type for the MetricsSender type
type MetricsSender struct {
	mock.Mock
}

// SendData provides a mock function with given fields: mType, name, value
func (_m *MetricsSender) SendData(mType string, name string, value string) error {
	ret := _m.Called(mType, name, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(mType, name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMetricsSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewMetricsSender creates a new instance of MetricsSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMetricsSender(t mockConstructorTestingTNewMetricsSender) *MetricsSender {
	mock := &MetricsSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
