// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/domain/metrics.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"

	"github.com/stretchr/testify/mock"
)

type MockMetricsSender struct {
	mock.Mock
}

func (m *MockMetricsSender) SendData(ctx context.Context, mType string, name string, value string) error {
	return nil
}
func (m *MockMetricsSender) SendDataBatch(ctx context.Context, jsonData []byte) error {
	return nil
}
